apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.cronName }}
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.cronApp }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: registry-key
      volumes:
      - name: stackage-server-cron-volume
        secret:
          secretName:  {{ .Values.cronName }}-secret
      containers:
        - name: stackage-server-cron
          image: {{ .Values.image.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PGSTRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}
                key: PGCONN
          command:
            - bash
            - "-c"
            - |
              set -eux
              source /secret/aws.sh
              mkdir -p /work
              cd /work
              while true
              do
                date
                stack update
                /usr/local/bin/stackage-server-cron
                sleep 5m
              done
          volumeMounts:
            - name: stackage-server-cron-volume
              readOnly: true
              mountPath: /secret
          resources:
{{ toYaml .Values.cronResources.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
