resolver: lts-18.28
extra-deps:
- amazonka-1.6.1
- barrier-0.1.1
- classy-prelude-yesod-1.5.0
- unliftio-core-0.1.2.0
- yesod-gitrepo-0.3.0
- static-bytes-0.1.0
- companion-0.1.0
- aeson-warning-parser-0.1.0
- git: https://github.com/commercialhaskell/pantry.git
  commit: 8e771ed7178d3b0948cba06f307455c2ca1b5e53

drop-packages:
- Cabal
