jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: |
      set -ex
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      export PATH=$HOME/.local/bin:$PATH

      sudo apt-get update
      sudo apt-get install libpq-dev

      stack test --interleaved-output
      set +ex
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: Installation
